Export types in package.json
Configured according to
https://kit.svelte.dev/docs/packaging#anatomy-of-a-package-json-exports

I've tested it locally by importing this package into a SvelteKit v2
project. The error I was resolving was:

../src/lib/figma/navigation/AvatarVariant.svelte:19:44
Error: Cannot find module 'svelte-boring-avatars' or its corresponding type declarations. (ts)
<script lang="ts">
    import { AvatarMarble as Avatar } from "svelte-boring-avatars";

Adding a types export into package.json resolves this

As similar error was reported by another person:
https://github.com/sveltejs/kit/issues/11329

The problem is with the imported package's exports, SvelteKit v2
switching to tsconfig module resolution to `bundler` brought the
underlying issue to the sruface.